# Generated by Django 3.2.4 on 2021-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encrypdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RawData', models.CharField(max_length=1000)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
